apiVersion: v1
kind: Pod
metadata:
  name: nginx-busybox
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    volumeMounts:
      - name: data
        mountPath: /var/log/nginx

  initContainers:
  - name: busybox
    image: busybox:latest
    command: ['sh', '-c', 'tail -F var/log/nginx/access.log']
    restartPolicy: Always
    volumeMounts:
      - name: data
        mountPath: /var/log/nginx

  volumes:
  - name: data
    emptyDir: {}